In [2]:
import pandas as pd
import numpy as np

In [2]:
mock_data = pd.read_csv("inputs/wtp_mock_data.csv")

In [10]:
mock_data.loc[:, 'website_visit'] = (mock_data.loc[:, 'website_visit'] / 10).astype(int)

In [18]:
mock_data.loc[:, 'checkout_rate'] = mock_data.loc[:, 'number_of_checkouts'] / mock_data.loc[:, 'website_visit'] * 100

In [20]:
7 * 650

4550

In [21]:
mock_data.loc[:, "daily_revenue_with_wtp"] = mock_data.loc[:, 'number_of_checkouts'] * mock_data.loc[:, 'WTP']

In [22]:
mock_data.groupby('class')["daily_revenue_with_wtp"].sum()

class
Business    125556.0
Economy     145747.0
Name: daily_revenue_with_wtp, dtype: float64

In [23]:
mock_data.groupby('class')["daily_revenue"].sum()

class
Business    125450.0
Economy     143780.0
Name: daily_revenue, dtype: float64

In [25]:
mock_data[mock_data['class'] == 'Economy']

,flight_number,class,origin,destination,departure_date,date,website_visit,number_of_checkouts,checkout_rate,DCP,class_dcp,air_fare_usd,daily_revenue,WTP,average_time_onsite,daily_revenue_with_wtp
0,CX6321,Economy,HND,HKG,2023-03-30,2023-03-01,88,7,7.954545,1,Economy_1,650.0,4550.0,590.0,13.576134,4130.0
2,CX6321,Economy,HND,HKG,2023-03-30,2023-03-02,86,6,6.976744,1,Economy_1,650.0,3900.0,586.0,14.694672,3516.0
4,CX6321,Economy,HND,HKG,2023-03-30,2023-03-03,89,5,5.617978,1,Economy_1,650.0,3250.0,661.0,18.442602,3305.0
6,CX6321,Economy,HND,HKG,2023-03-30,2023-03-04,90,4,4.444444,1,Economy_1,650.0,2600.0,571.0,11.748785,2284.0
8,CX6321,Economy,HND,HKG,2023-03-30,2023-03-05,91,6,6.593407,1,Economy_1,650.0,3900.0,765.0,18.892729,4590.0
10,CX6321,Economy,HND,HKG,2023-03-30,2023-03-06,87,9,10.344828,2,Economy_2,845.0,7605.0,981.0,15.744968,8829.0
12,CX6321,Economy,HND,HKG,2023-03-30,2023-03-07,91,5,5.494505,2,Economy_2,845.0,4225.0,987.0,23.802076,4935.0
14,CX6321,Economy,HND,HKG,2023-03-30,2023-03-08,97,3,3.092784,2,Economy_2,845.0,2535.0,961.0,10.833870,2883.0
16,CX6321,Economy,HND,HKG,2023-03-30,2023-03-09,92,5,5.434783,2,Economy_2,845.0,4225.0,980.0,15.238290,4900.0
18,CX6321,Economy,HND,HKG,2023-03-30,2023-03-10,94,7,7.446809,2,Economy_2,845.0,5915.0,727.0,12.995640,5089.0
20,CX6321,Economy,HND,HKG,2023-03-30,2023-03-11,91,5,5.494505,2,Economy_2,845.0,4225.0,740.0,20.409800,3700.0
22,CX6321,Economy,HND,HKG,2023-03-30,2023-03-12,96,7,7.291667,2,Economy_2,845.0,5915.0,858.0,10.953810,6006.0
24,CX6321,Economy,HND,HKG,2023-03-30,2023-03-13,95,12,12.631579,3,Economy_3,780.0,9360.0,972.0,12.714551,11664.0
26,CX6321,Economy,HND,HKG,2023-03-30,2023-03-14,95,5,5.263158,3,Economy_3,780.0,3900.0,882.0,13.334902,4410.0
28,CX6321,Economy,HND,HKG,2023-03-30,2023-03-15,91,4,4.395604,3,Economy_3,780.0,3120.0,807.0,24.796759,3228.0
30,CX6321,Economy,HND,HKG,2023-03-30,2023-03-16,96,4,4.166667,3,Economy_3,780.0,3120.0,642.0,24.321200,2568.0
32,CX6321,Economy,HND,HKG,2023-03-30,2023-03-17,95,13,13.684211,3,Economy_3,780.0,10140.0,650.0,24.759168,8450.0
34,CX6321,Economy,HND,HKG,2023-03-30,2023-03-18,101,5,4.950495,3,Economy_3,780.0,3900.0,813.0,16.689765,4065.0
36,CX6321,Economy,HND,HKG,2023-03-30,2023-03-19,100,5,5.000000,3,Economy_3,780.0,3900.0,619.0,21.336873,3095.0
38,CX6321,Economy,HND,HKG,2023-03-30,2023-03-20,95,3,3.157895,4,Economy_4,975.0,2925.0,1081.0,16.097802,3243.0
40,CX6321,Economy,HND,HKG,2023-03-30,2023-03-21,101,8,7.920792,4,Economy_4,975.0,7800.0,1064.0,18.902016,8512.0
42,CX6321,Economy,HND,HKG,2023-03-30,2023-03-22,100,9,9.000000,4,Economy_4,975.0,8775.0,787.0,21.707543,7083.0
44,CX6321,Economy,HND,HKG,2023-03-30,2023-03-23,98,3,3.061224,4,Economy_4,975.0,2925.0,913.0,14.990594,2739.0
46,CX6321,Economy,HND,HKG,2023-03-30,2023-03-24,103,5,4.854369,4,Economy_4,975.0,4875.0,1130.0,16.392246,5650.0
48,CX6321,Economy,HND,HKG,2023-03-30,2023-03-25,100,4,4.000000,4,Economy_4,975.0,3900.0,792.0,10.267132,3168.0
50,CX6321,Economy,HND,HKG,2023-03-30,2023-03-26,99,7,7.070707,4,Economy_4,975.0,6825.0,1129.0,17.573229,7903.0
52,CX6321,Economy,HND,HKG,2023-03-30,2023-03-27,102,1,0.980392,5,Economy_5,1105.0,1105.0,1169.0,11.489133,1169.0
54,CX6321,Economy,HND,HKG,2023-03-30,2023-03-28,101,5,4.950495,5,Economy_5,1105.0,5525.0,1125.0,18.294472,5625.0
56,CX6321,Economy,HND,HKG,2023-03-30,2023-03-29,95,4,4.210526,5,Economy_5,1105.0,4420.0,951.0,15.282742,3804.0
58,CX6321,Economy,HND,HKG,2023-03-30,2023-03-30,101,4,3.960396,5,Economy_5,1105.0,4420.0,1301.0,13.047870,5204.0

In [11]:
mock_data = pd.read_csv("inputs/wtp_mock_data3.csv")

In [15]:
mock_data.to_csv("inputs/wtp_mock_data4.csv")

In [13]:
mock_data['date'] = pd.to_datetime(mock_data['date']) - pd.Timedelta(days=22)

In [14]:
mock_data

,flight_number,class,origin,destination,departure_date,date,website_visit,number_of_checkouts,checkout_rate,DCP,class_dcp,air_fare_usd,daily_revenue,WTP2,average_time_onsite
0,NZ631,Economy,AKL,SYD,2023-08-30,2023-07-10,76,4,5.263158,1,Economy_1,650.0,2600.0,526.50,20.856683
1,NZ631,Business,AKL,SYD,2023-08-30,2023-07-10,35,2,5.714286,1,Business_1,3250.0,6500.0,3250.00,20.856683
2,NZ631,Economy,AKL,SYD,2023-08-30,2023-07-11,93,5,5.376344,1,Economy_1,650.0,3250.0,637.00,13.736078
3,NZ631,Business,AKL,SYD,2023-08-30,2023-07-11,35,0,0.000000,1,Business_1,3250.0,0.0,3250.00,13.736078
4,NZ631,Economy,AKL,SYD,2023-08-30,2023-07-12,94,5,5.319149,1,Economy_1,650.0,3250.0,643.50,23.094944
5,NZ631,Business,AKL,SYD,2023-08-30,2023-07-12,38,0,0.000000,1,Business_1,3250.0,0.0,3347.50,23.094944
6,NZ631,Economy,AKL,SYD,2023-08-30,2023-07-13,80,3,3.750000,1,Economy_1,650.0,1950.0,552.50,14.368891
7,NZ631,Business,AKL,SYD,2023-08-30,2023-07-13,37,3,8.108108,1,Business_1,3250.0,9750.0,3315.00,14.368891
8,NZ631,Economy,AKL,SYD,2023-08-30,2023-07-14,82,5,6.097561,1,Economy_1,650.0,3250.0,565.50,12.969231
9,NZ631,Business,AKL,SYD,2023-08-30,2023-07-14,32,2,6.250000,1,Business_1,3250.0,6500.0,3152.50,12.969231
10,NZ631,Economy,AKL,SYD,2023-08-30,2023-07-15,84,1,1.190476,1,Economy_1,650.0,650.0,578.50,20.399136
11,NZ631,Business,AKL,SYD,2023-08-30,2023-07-15,33,2,6.060606,1,Business_1,3250.0,6500.0,3185.00,20.399136
12,NZ631,Economy,AKL,SYD,2023-08-30,2023-07-16,97,4,4.123711,2,Economy_2,845.0,3380.0,861.90,13.216234
13,NZ631,Business,AKL,SYD,2023-08-30,2023-07-16,39,1,2.564103,2,Business_2,4225.0,4225.0,4394.00,13.216234
14,NZ631,Economy,AKL,SYD,2023-08-30,2023-07-17,99,3,3.030303,2,Economy_2,845.0,2535.0,878.80,22.388968
15,NZ631,Business,AKL,SYD,2023-08-30,2023-07-17,37,1,2.702703,2,Business_2,4225.0,4225.0,4309.50,22.388968
16,NZ631,Economy,AKL,SYD,2023-08-30,2023-07-18,85,3,3.529412,2,Economy_2,845.0,2535.0,760.50,20.761787
17,NZ631,Business,AKL,SYD,2023-08-30,2023-07-18,41,1,2.439024,2,Business_2,4225.0,4225.0,4478.50,20.761787
18,NZ631,Economy,AKL,SYD,2023-08-30,2023-07-19,89,3,3.370787,2,Economy_2,845.0,2535.0,794.30,19.492642
19,NZ631,Business,AKL,SYD,2023-08-30,2023-07-19,40,0,0.000000,2,Business_2,4225.0,0.0,4436.25,19.492642
20,NZ631,Economy,AKL,SYD,2023-08-30,2023-07-20,84,3,3.571429,2,Economy_2,845.0,2535.0,752.05,23.519877
21,NZ631,Business,AKL,SYD,2023-08-30,2023-07-20,38,1,2.631579,2,Business_2,4225.0,4225.0,4351.75,23.519877
22,NZ631,Economy,AKL,SYD,2023-08-30,2023-07-21,97,7,7.216495,2,Economy_2,845.0,5915.0,861.90,21.920971
23,NZ631,Business,AKL,SYD,2023-08-30,2023-07-21,32,1,3.125000,2,Business_2,4225.0,4225.0,4098.25,21.920971
24,NZ631,Economy,AKL,SYD,2023-08-30,2023-07-22,98,5,5.102041,2,Economy_2,845.0,4225.0,870.35,23.013071
25,NZ631,Business,AKL,SYD,2023-08-30,2023-07-22,34,0,0.000000,2,Business_2,4225.0,0.0,4182.75,23.013071
26,NZ631,Economy,AKL,SYD,2023-08-30,2023-07-23,103,4,3.883495,3,Economy_3,780.0,3120.0,842.40,14.090180
27,NZ631,Business,AKL,SYD,2023-08-30,2023-07-23,42,0,0.000000,3,Business_3,3900.0,0.0,4173.00,14.090180
28,NZ631,Economy,AKL,SYD,2023-08-30,2023-07-24,100,2,2.000000,3,Economy_3,780.0,1560.0,819.00,17.253725
29,NZ631,Business,AKL,SYD,2023-08-30,2023-07-24,39,1,2.564103,3,Business_3,3900.0,3900.0,4056.00,17.253725
30,NZ631,Economy,AKL,SYD,2023-08-30,2023-07-25,100,2,2.000000,3,Economy_3,780.0,1560.0,819.00,20.056814
31,NZ631,Business,AKL,SYD,2023-08-30,2023-07-25,33,0,0.000000,3,Business_3,3900.0,0.0,3822.00,20.056814
32,NZ631,Economy,AKL,SYD,2023-08-30,2023-07-26,101,1,0.990099,3,Economy_3,780.0,780.0,826.80,19.664159
33,NZ631,Business,AKL,SYD,2023-08-30,2023-07-26,40,2,5.000000,3,Business_3,3900.0,7800.0,4095.00,19.664159
34,NZ631,Economy,AKL,SYD,2023-08-30,2023-07-27,101,1,0.990099,3,Economy_3,780.0,780.0,826.80,24.124998
35,NZ631,Business,AKL,SYD,2023-08-30,2023-07-27,34,0,0.000000,3,Business_3,3900.0,0.0,3861.00,24.124998
36,NZ631,Economy,AKL,SYD,2023-08-30,2023-07-28,88,1,1.136364,3,Economy_3,780.0,780.0,725.40,12.426697
37,NZ631,Business,AKL,SYD,2023-08-30,2023-07-28,42,2,4.761905,3,Business_3,3900.0,7800.0,4173.00,12.426697
38,NZ631,Economy,AKL,SYD,2023-08-30,2023-07-29,107,3,2.803738,3,Economy_3,780.0,2340.0,873.60,15.294432
39,NZ631,Business,AKL,SYD,2023-08-30,2023-07-29,37,0,0.000000,3,Business_3,3900.0,0.0,3978.00,15.294432
40,NZ631,Economy,AKL,SYD,2023-08-30,2023-07-30,99,5,5.050505,4,Economy_4,975.0,4875.0,1014.00,17.986712
41,NZ631,Business,AKL,SYD,2023-08-30,2023-07-30,34,1,2.941176,4,Business_4,4875.0,4875.0,4826.25,17.986712
42,NZ631,Economy,AKL,SYD,2023-08-30,2023-07-31,97,4,4.123711,4,Economy_4,975.0,3900.0,994.50,20.079588
43,NZ631,Business,AKL,SYD,2023-08-30,2023-07-31,42,1,2.380952,4,Business_4,4875.0,4875.0,5216.25,20.079588
44,NZ631,Economy,AKL,SYD,2023-08-30,2023-08-01,91,4,4.395604,4,Economy_4,975.0,3900.0,936.00,11.039088
45,NZ631,Business,AKL,SYD,2023-08-30,2023-08-01,43,2,4.651163,4,Business_4,4875.0,9750.0,5265.00,11.039088
46,NZ631,Economy,AKL,SYD,2023-08-30,2023-08-02,104,6,5.769231,4,Economy_4,975.0,5850.0,1062.75,24.235632
47,NZ631,Business,AKL,SYD,2023-08-30,2023-08-02,38,1,2.631579,4,Business_4,4875.0,4875.0,5021.25,24.235632
48,NZ631,Economy,AKL,SYD,2023-08-30,2023-08-03,104,1,0.961538,4,Economy_4,975.0,975.0,1062.75,21.338592
49,NZ631,Business,AKL,SYD,2023-08-30,2023-08-03,37,0,0.000000,4,Business_4,4875.0,0.0,4972.50,21.338592
50,NZ631,Economy,AKL,SYD,2023-08-30,2023-08-04,99,4,4.040404,4,Economy_4,975.0,3900.0,1014.00,24.319262
51,NZ631,Business,AKL,SYD,2023-08-30,2023-08-04,41,1,2.439024,4,Business_4,4875.0,4875.0,5167.50,24.319262
52,NZ631,Economy,AKL,SYD,2023-08-30,2023-08-05,89,3,3.370787,4,Economy_4,975.0,2925.0,916.50,21.462334
53,NZ631,Business,AKL,SYD,2023-08-30,2023-08-05,40,0,0.000000,4,Business_4,4875.0,0.0,5118.75,21.462334
54,NZ631,Economy,AKL,SYD,2023-08-30,2023-08-06,102,3,2.941176,5,Economy_5,1105.0,3315.0,1182.35,21.158872
55,NZ631,Business,AKL,SYD,2023-08-30,2023-08-06,35,2,5.714286,5,Business_5,5525.0,11050.0,5525.00,21.158872
56,NZ631,Economy,AKL,SYD,2023-08-30,2023-08-07,103,1,0.970874,5,Economy_5,1105.0,1105.0,1193.40,17.828487
57,NZ631,Business,AKL,SYD,2023-08-30,2023-08-07,37,1,2.702703,5,Business_5,5525.0,5525.0,5635.50,17.828487
58,NZ631,Economy,AKL,SYD,2023-08-30,2023-08-08,102,4,3.921569,5,Economy_5,1105.0,4420.0,1182.35,24.939842
59,NZ631,Business,AKL,SYD,2023-08-30,2023-08-08,43,2,4.651163,5,Business_5,5525.0,11050.0,5967.00,24.939842